### PR TITLE
thread-safe group controller

### LINKED ISSUE #61: driver crashes (sometimes) due to switching controllers in velocity mode
a) this one works:
roslaunch cob_bringup robot.launch
init
rosservice call /arm_left/controller_manager/switch_controllers (stop_controllers = joint_trajectory_controller, start_controllers = joint_group_velocity_controller)

b) this one crashes (sometimes, but very often):
roslaunch cob_bringup robot.launch
init
rostopic pub /arm_left/joint_group_velocity_controller/command std_msgs/Float64MultiArray ...

The difference between a) and b) is that in a) we're only switching controllers and in b) we're switching controllers while publishing velocities. There are two subscribers (cob_control_mode_adapter and canopen driver) for the velocity topic. So the crash might be caused by a race condition when a callback in the driver is executed before the callback and switch in the cob_control_mode_adapter has finished successfully.
@thiagodefreitas: can you please investigate that on monday?
If that's true, the driver should ignore all velocity inputs as long as not all modules are switched successfully to velocity mode (initiated by the cob_control_mode_adapter). 

@ipa-mdl: FYI

### PR DESCRIPTION
**Pull request by mathias-luedtke**
thread-safe group controller that resolves https://github.com/ipa320/ros_canopen/issues/61 and fixes issues with potentially mixed commands
to be tested..
- thread-safe/realtime-safe topic handling
- check for empty list of joints
- properly resets to neutral zeros at restart (resize only works the first time)

### CODE REVIEW

**Comment by floweisshardt** [comment]
@thiagodefreitas: please test this and report the results here

**Comment by floweisshardt** [comment]
@thiagodefreitas: did you test this?
@ipa-mdl: this cannot be merged any more. please merge with current ipa320/indigo_dev first.

**Comment by thiagodefreitas** [comment]
@ipa-fmw I have been using that for almost 2 weeks now without any problem.

**Comment by mathias-luedtke** [comment]
It is already merged upstream into into ros-controls/ros_controllers  :)
Currently we do not need this fork, it could be removed or reset.

**Comment by floweisshardt** [comment]
ok, this means I'll close this PR

**Pull request closed without merging**
